#ifndef ___WEA_H___
#define ___WEA_H___

#define KIR_N  0
#define GUN_N  1
#define PLM_N  2
#define SHK_N  3
#define TAZ_N  4
#define ROC_N  5
#define MAV_N  6
#define MIN_N  7
#define BLD_N  8
#define HOL_N  9
#define TEL_N 10

#define KIR_FZ  9
#define GUN_FZ 20
#define PLM_FZ 11
#define SHK_FZ  7
#define TAZ_FZ 26
#define ROC_FZ 22
#define MAV_FZ 33
#define MIN_FZ 15
#define BLD_FZ 10
#define HOL_FZ  5
#define TEL_FZ 16

#define EXPL_INV 1
#define EXPL_NMG 2
#define EXPL_TEL 4
#define EXPL_MSK 64

#define POW_KIR   120
#define POW_GUN   130
#define POW_PLM    60
#define POW_SHOCK  64
#define POW_TAZER  12
#define POW_MIS    96
#define POW_MAV    45
#define POW_MINE  190
#define POW_PTL    64

#define DIE_INWALL   24
#define DIE_ON_INCUB 14

#define POW_BARREL 70
#define POW_OBL    90
#define POW_NAPALM 80
#define POW_INCUBATOR 70

#endif